apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: hello-webapp
        image: f532-35-205-93-167.eu.ngrok.io/hello-webapp:latest
        ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 22
      imagePullSecrets:
      - name: nexus-pull-secret
  
