apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: hello-webapp
        image: kaylan44/hello-webapp:latest
        ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 22
